# Generated by Django 2.2.3 on 2019-11-25 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_delete_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='quickreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('fee', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('explane', models.CharField(max_length=254, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_paied', models.DateTimeField(null=True)),
            ],
        ),
    ]
