# Generated by Django 2.2.3 on 2019-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_quickreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
