# Generated by Django 2.2.3 on 2019-12-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
