# Generated by Django 2.2.3 on 2020-10-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOnServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='موضوع تیکت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته\u200cشده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceModel', verbose_name='خدمت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت مربوط به خدمات',
                'verbose_name_plural': 'تیکت\u200cهای مربوط به خدمات',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Ticket_images')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
