# Generated by Django 2.2.5 on 2020-08-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstShoppingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('Pname', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='FirstCategoryShop_image')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('Pname', models.CharField(max_length=50)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('Pname', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('Link', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('firstShoppingCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.FirstShoppingCategory')),
            ],
        ),
        migrations.AddField(
            model_name='firstshoppingcategory',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Title'),
        ),
    ]
