# Generated by Django 2.2.3 on 2020-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام خدمت')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ خدمت')),
                ('thumbnail_service', models.ImageField(blank=True, null=True, upload_to='service-thumbnails', verbose_name='تصویر شاخص')),
            ],
            options={
                'verbose_name': 'مشخصات خدمت',
                'verbose_name_plural': 'مشخصات خدمات',
            },
        ),
    ]
