# Generated by Django 2.2.3 on 2020-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_subject_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coveid19',
        ),
    ]
