# Generated by Django 2.2.3 on 2020-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_coveid19'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='testfield',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
