# Generated by Django 2.2.3 on 2020-04-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_topic_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='testfield',
        ),
    ]
