# Generated by Django 2.2.3 on 2020-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
