# Generated by Django 2.2.3 on 2020-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200421_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Ename',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Pname',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Ename',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Pname',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
