# Generated by Django 2.2.3 on 2019-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreservation',
            name='string',
            field=models.CharField(default='', max_length=50),
        ),
    ]
