# Generated by Django 2.2.3 on 2019-11-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191125_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoppingitem',
        ),
    ]
