# Generated by Django 2.2.3 on 2019-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_delete_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthreservation',
            name='time_paied',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resonancereservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resonancereservation',
            name='time_paied',
            field=models.DateTimeField(null=True),
        ),
    ]
