# Generated by Django 2.2.3 on 2019-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20191204_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreservation',
            name='visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resonancereservation',
            name='visit',
            field=models.BooleanField(default=False),
        ),
    ]
