# Generated by Django 2.2.3 on 2019-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20191222_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreservation',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='health_results'),
        ),
        migrations.AddField(
            model_name='resonancereservation',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='resonance_results'),
        ),
    ]
