# Generated by Django 2.2.3 on 2020-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20191226_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='resonancereservation',
            name='category',
            field=models.CharField(choices=[('Resonance', 'رزونانس'), ('Frequency', 'فرکانس')], default='Resonance', max_length=20),
        ),
    ]
