# Generated by Django 2.2.3 on 2020-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_resonancereservation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resonancereservation',
            name='result2',
            field=models.FileField(blank=True, default='', upload_to='resonance_results'),
        ),
        migrations.AddField(
            model_name='resonancereservation',
            name='result3',
            field=models.FileField(blank=True, default='', upload_to='resonance_results'),
        ),
        migrations.AlterField(
            model_name='resonancereservation',
            name='result',
            field=models.FileField(blank=True, default='', upload_to='resonance_results'),
        ),
    ]
