# Generated by Django 2.2.3 on 2020-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20201026_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreservation',
            name='result2',
            field=models.FileField(blank=True, default='', upload_to='health_results'),
        ),
        migrations.AddField(
            model_name='healthreservation',
            name='result3',
            field=models.FileField(blank=True, default='', upload_to='health_results'),
        ),
        migrations.AlterField(
            model_name='healthreservation',
            name='result',
            field=models.FileField(blank=True, default='', upload_to='health_results'),
        ),
    ]
