# Generated by Django 2.2.3 on 2020-12-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20201026_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthreservation',
            options={'verbose_name': 'رزرو هلث', 'verbose_name_plural': 'رزروهای هلث'},
        ),
        migrations.AlterModelOptions(
            name='resonancereservation',
            options={'verbose_name': 'رزرو ای\u200cدی\u200cاس', 'verbose_name_plural': 'رزروهای ای\u200cدی\u200cاس'},
        ),
    ]
