# Generated by Django 2.2.1 on 2019-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('fa_title', models.CharField(default='', max_length=50)),
                ('en_title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='en_q',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='details',
            name='fa_q',
            field=models.CharField(default='', max_length=500),
        ),
    ]
