# Generated by Django 2.2.1 on 2019-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20191002_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='response',
            field=models.CharField(default='', max_length=50),
        ),
    ]
