# Generated by Django 2.2.3 on 2019-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20191002_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='response',
            field=models.CharField(default='', max_length=30),
        ),
    ]
