# Generated by Django 2.2.5 on 2019-10-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20191024_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesscircle',
            name='totalquiz',
            field=models.CharField(default='', max_length=100),
        ),
    ]
