# Generated by Django 2.2.5 on 2019-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20191024_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='response',
            field=models.CharField(default='', max_length=50),
        ),
    ]
