# Generated by Django 2.2.3 on 2019-12-08 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20191024_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesscircle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
