# Generated by Django 2.2.3 on 2019-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20191208_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
