# Generated by Django 2.2.3 on 2019-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20191208_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
