# Generated by Django 2.2.3 on 2019-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20191208_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='test',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnesscircle',
            name='test',
            field=models.CharField(max_length=50),
        ),
    ]
