# Generated by Django 2.2.3 on 2019-12-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20191208_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnesscircle',
            name='test',
        ),
    ]
