# Generated by Django 2.2.3 on 2019-12-08 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_wellnesscircle_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='test',
        ),
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
