# Generated by Django 2.2.3 on 2019-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20191208_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='result',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
