# Generated by Django 2.2.3 on 2019-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_wellnesscircle_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='imageresult',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_results_12dimensions'),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='imageresult',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_results_wellnessCircle'),
        ),
    ]
