# Generated by Django 2.2.3 on 2019-12-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20191229_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='pdfresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_12dimensions/file'),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='pdfresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_wellnessCircle/file'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='imageresult',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_results_12dimensions/image'),
        ),
        migrations.AlterField(
            model_name='wellnesscircle',
            name='imageresult',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_results_wellnessCircle/image'),
        ),
    ]
