# Generated by Django 2.2.3 on 2019-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20191229_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='avresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_12dimensions/audio-video'),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='avresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_wellnessCircle/audio-video'),
        ),
    ]
