# Generated by Django 2.2.3 on 2020-01-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20191229_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='avresult',
        ),
        migrations.RemoveField(
            model_name='wellnesscircle',
            name='avresult',
        ),
        migrations.AddField(
            model_name='submit',
            name='audioresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_12dimensions/audio'),
        ),
        migrations.AddField(
            model_name='submit',
            name='videoresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_12dimensions/video'),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='audioresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_wellnessCircle/audio'),
        ),
        migrations.AddField(
            model_name='wellnesscircle',
            name='videoresult',
            field=models.FileField(blank=True, null=True, upload_to='quiz_results_wellnessCircle/video'),
        ),
    ]
