# Generated by Django 2.2.3 on 2021-02-10 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_verification_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='1.1.1.1')),
                ('phone_number', models.CharField(max_length=12)),
                ('key', models.CharField(max_length=5)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد فعالسازی',
                'verbose_name_plural': 'کدهای فعالسازی',
            },
        ),
        migrations.CreateModel(
            name='profiledb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellid', models.CharField(blank=True, default='', max_length=15, verbose_name='کد ولنسی')),
                ('membershipType', models.CharField(blank=True, default='Normal', max_length=10, verbose_name='نوع عضویت کاربر')),
                ('firstname', models.CharField(default='', max_length=20, verbose_name='نام')),
                ('lastname', models.CharField(default='', max_length=20, verbose_name='نام خانوادگی')),
                ('Email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address1', models.CharField(blank=True, default='', max_length=254, verbose_name='آدرس منزل')),
                ('phone1', models.CharField(blank=True, default='', max_length=11, verbose_name='تلفن ثابت')),
                ('job', models.CharField(blank=True, default='', max_length=20, verbose_name='شغل')),
                ('address2', models.CharField(blank=True, default='', max_length=254, verbose_name='آدرس حدودی محل کار')),
                ('phone3', models.CharField(blank=True, default='', max_length=11, verbose_name='شماره شبکه\u200cهای اجتماعی')),
                ('image', models.ImageField(blank=True, default='', upload_to='ProfileImage', verbose_name='تصویر پروفایل')),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشخصات کاربری',
                'verbose_name_plural': 'مشخصات کاربرها',
            },
        ),
    ]
